name: 拉取所有源

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */12 * * *'
  workflow_dispatch:

pobing:
  jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 克隆仓库
        run: |
          origin=https://github.com/PB-pobing/pobing
          folder=pobing
          echo $origin to $folder
          sudo apt install git
          cd ${GITHUB_WORKSPACE}
          sudo rm -rf $folder
          mkdir $folder
          cd $folder
          git clone $origin .

          sudo rm -rf .git

          mv sy.json sources.json
          mv 50.json 50-sources.json
          echo 书源来源于$origin>origin.md
          cd ..
      - name: 提交更新
        # You may pin to the exact commit or the version.
        # uses: actions-x/commit@803b20e5b72c0425eb7919c42c321e67c5bc5d2d
        uses: actions-x/commit@v6
        with: 
          commit_message: "更新破冰源"
yi-c:
  jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 克隆仓库
        run: |
          origin=https://gitlink.org.cn/yi-c/yd.git
          folder=yi-c
          echo $origin to $folder
          sudo apt install git
          cd ${GITHUB_WORKSPACE}
          sudo rm -rf $folder
          mkdir $folder
          cd $folder
          git clone $origin .

          sudo rm -rf .github .git

          mv sy.json sources.json
          mv dy.json subscribe.json
          echo 书源来源于$origin>origin.md
          cd ..
      - name: 提交更新
        # You may pin to the exact commit or the version.
        # uses: actions-x/commit@803b20e5b72c0425eb7919c42c321e67c5bc5d2d
        uses: actions-x/commit@v6
        with: 
          commit_message: "更新一程、源"

april:
  jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 克隆仓库
        run: |
            rm -rf 人间的四月天
            mkdir 人间的四月天
            cd 人间的四月天
            sudo apt install unzip curl wget jq
            json=$(curl -s "https://cloud.humorously.cn/api/api.php?link=https://xiahanyun.lanzoum.com/b030q8wyj&pwd=1234")
            filename=$(echo "$json" | jq -r '.data[0].name')
            url=$(echo "$json" | jq -r '.data[0].url')
            echo "文件名: $filename"
            echo "链接: $url"
            wget -O sy.zip $url
            unzip sy.zip
            mv booksource.json sources.json
            rm -rf sy.zip
            echo 来源：https://xiahanyun.lanzoum.com/b030q8wyj 密码：1234>origin.md
            cd ..
      - name: 提交更新
        # You may pin to the exact commit or the version.
        # uses: actions-x/commit@803b20e5b72c0425eb7919c42c321e67c5bc5d2d
        uses: actions-x/commit@v6
        with: 
          commit_message: "更新四月天源"

xiu2:
  jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 克隆仓库
        run: |
          origin=https://github.com/XIU2/Yuedu
          folder=xiu2
          echo $origin to $folder
          sudo apt install git
          cd ${GITHUB_WORKSPACE}
          sudo rm -rf $folder
          mkdir $folder
          cd $folder
          git clone $origin .

          sudo rm -rf .github .nojekyll .gitattributes .git
          shopt -s extglob
          sudo rm -rf !(LICENSE|README.md|shuyuan)

          mv shuyuan sources.json
          echo 书源来源于$origin>origin.md
          cd ..
      - name: 提交更新
        # You may pin to the exact commit or the version.
        # uses: actions-x/commit@803b20e5b72c0425eb7919c42c321e67c5bc5d2d
        uses: actions-x/commit@v6
        with: 
          commit_message: "更新XIU2源"